### ISSUE TITLE
Ensure the FBC --> entity translation for bundle properties is not lossy

### ISSUE THREAD

**Issue by everettraven** [operator-framework/operator-controller#258] opened 2023-06-08 14:52 UTC
Currently the translation for catalog contents --> entity is lossy when it comes to bundle properties. As we can see from https://github.com/operator-framework/operator-controller/blob/80a5786d9a9335392d35e715b4956a93b9fd64c9/internal/resolution/entitysources/catalogdsource.go#L83-L90 we are only passing through bundle properties that are of type `olm.package` and therefore losing any other bundle property information.

We should update this to ensure that all bundle properties are being forwarded through during the entity translation so they can be used properly.

**Comment by joelanford** [comment] 2023-06-08 16:35
@perdasilva This seems like a rough edge of the translation from FBC to `input.Entity`. I know the `Properties []property.Property` field in FBC is problematic, but it seems more problematic that we don't have an opaque canonical translation function.

Another option would be to have `input.Entity` change its properties field to match (and maybe translate internally)?

Either way, I think we need to smooth out this edge.

**Comment by m1kola** [comment] 2023-06-09 10:22
Today properties on a Deppy `input.Entity`  are defined as [a map of strings](https://github.com/operator-framework/deppy/blob/cbf2c66b141b9968935a7f9e43d7269ea7fe9e6f/pkg/deppy/input/entity.go#L9). But in operator-controller I think we can pack anything we want into this map in any format we want: we don’t have to change Deppy for operator-controller to understand repeated properties as Deppy itself is not reading properties (but we consider change to avoid weird marshalling on controller side). And `BundleMetadataSpec` already has properties as a slice. So to me it looks like the ball is entirely on the operator-controller side.

**Comment by perdasilva** [comment] 2023-06-12 15:45
+1 to @m1kola: I think this fix should go in op-controller. Entities are dumb by design. Though, they might go away. I'd say the right way to fix this would be to just laydown a json string in the property - and copy all of the properties over.

**Comment by m1kola** [comment] 2023-09-21 12:51
In #413 we got rid of entity source & entity code and now have access to all bundle props, but there is currently an issue on read where we lose some values. Once #427 gets merged, I think we can consider this done.

**Comment by m1kola** [comment] 2023-09-21 13:50
#427 is merged now. For some reason GH didn't close the issue, so I'm doing it manually.

**Closed by m1kola** 2023-09-21 13:50 UTC
